### ISSUE TITLE
to_send string not cleared in _finish()

### ISSUE THREAD

**Issue by aschulm** [ppannuto/python-saleae#1]
How to reproduce:

  logic = saleae.Saleae()
  logic.set_active_channels([7], [0,1,2,3,4,5,6])
  logic.set_capture_seconds(options.trace_time)
  logic.set_sample_rate_by_minimum(1e6, 10e3)
  logic.set_triggers_for_all_channels([
    saleae.Trigger.NoTrigger,
    saleae.Trigger.NoTrigger,
    saleae.Trigger.NoTrigger,
    saleae.Trigger.NoTrigger,
    saleae.Trigger.NoTrigger,
    saleae.Trigger.NoTrigger,
    saleae.Trigger.NoTrigger,
    saleae.Trigger.Posedge
  ])

Traceback (most recent call last):
  File "./trace-xu3.py", line 396, in <module>
    main()
  File "./trace-xu3.py", line 195, in main
    saleae.Trigger.Posedge
  File "/home/aschulm/Projects/battor_research/third_party/python-saleae/saleae/saleae.py", line 145, in set_triggers_for_all_channels
    self._finish()
  File "/home/aschulm/Projects/battor_research/third_party/python-saleae/saleae/saleae.py", line 88, in _finish
    return self._cmd(', '.join(self._to_send))
  File "/home/aschulm/Projects/battor_research/third_party/python-saleae/saleae/saleae.py", line 113, in _cmd
    return self._recv()
  File "/home/aschulm/Projects/battor_research/third_party/python-saleae/saleae/saleae.py", line 106, in _recv
    raise self.CommandNAKedError
saleae.CommandNAKedError

How to solve:

self._to_send = [] in finish().

*I'd be happy to fix if you add me as a contributor.

**Comment by ppannuto** [comment]
Please do
