### ISSUE TITLE
get_capture_range throws ValueError

### ISSUE THREAD

**Issue by tamenol** [ppannuto/python-saleae#72]
I use the following code snippet:

```
from saleae import Saleae, Trigger

s = Saleae()
s.set_active_channels(digital=[0], analog=[1])
s.set_sample_rate((500000000, 50000000))
s.set_digital_voltage_option(2)
s.set_trigger_one_channel(digital_channel=0, trigger=Trigger.Posedge)
s.set_capture_seconds(0.4)
s.capture_start_and_wait_until_finished()
s.get_capture_range()
```

This results in:
```
>>> INFO:saleae.saleae:Connected.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:/Users/X.X/Documents/project/capture.py", line 10, in <module>
    s.get_capture_range()
  File "C:\Users\X.X\AppData\Roaming\Python\Python39\site-packages\saleae\saleae.py", line 755, in get_capture_range
    index_samples = list(map(int, map(str.strip, indexes.split(','))))
ValueError: invalid literal for int() with base 10: 'TRUE'
```

This is in W10 with Python3.9

**Comment by tamenol** [comment]
The particular function got added in #69
